- name: package update
  ansible.builtin.apt:
    update_cache: true
- name: Install required packages
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes