- name: package update
  apt:
    update_cache: true
- name: Install required packages
  package:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
- name: Ensure PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes